# Install tmux-yank
set -g @plugin 'tmux-plugins/tmux-yank'

# Editing mode: vi
setw -g mode-keys vi

# Prefix (Emacs-style)
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Global colour settings
set -g default-terminal "screen-256color"
set -g status-fg black
set -g status-bg green
setw -g window-status-attr dim
setw -g window-status-fg black
setw -g window-status-bg green
setw -g window-status-current-fg yellow
setw -g window-status-current-bg red
setw -g window-status-current-attr bright
set -g pane-border-fg red
set -g pane-border-bg default
set -g pane-active-border-fg yellow
set -g pane-active-border-bg default

# Status to be centred
set -g status-justify centre

# Timeout set to 1 second
set -s escape-time 1

# Key bindgins: config reload
bind r source-file ~/.tmux.conf \; display "Config reload!"

# Indices to start at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Key bindings: window split
bind | split-window -h
bind \ split-window -h
bind - split-window -v

# Key bindings: pane navigation (Emacs-style)
bind -r b select-pane -L
bind -r n select-pane -D
bind -r p select-pane -U
bind -r f select-pane -R

# Key bindings: window navigation (Emacs-style)
bind -r N select-window -t :+
bind -r P select-window -t :-

# Key bindings: pane resizing (Emacs-style)
bind -r C-b resize-pane -L 5
bind -r C-n resize-pane -D 5
bind -r C-p resize-pane -U 5
bind -r C-f resize-pane -R 5

# Clipboard integration (OS X)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe "reattach-to-user-namespace pbcopy"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe "reattach-to-user-namespace pbcopy"

# No delay on Esc (for Vim)
set -sg escape-time 0
