set -g default-terminal "screen-256color"

set -g status-fg black
set -g status-bg green

setw -g window-status-attr dim

setw -g window-status-current-fg yellow
setw -g window-status-current-bg red
setw -g window-status-current-attr bright

set -g prefix C-a
unbind C-b

set -s escape-time 1

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on

bind r source-file ~/.tmux.conf \; display "config reloaded!"

bind | split-window -h
bind - split-window -v

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r K select-window -t :-
bind -r J select-window -t :+

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
